### ISSUE TITLE
linter executes rubocop on non-ruby files

### ISSUE THREAD

**Issue by alexanderadam** [AtomLinter/linter-rubocop#102]
For example markdown files.
Rubocop itself wouldn't check markdown files so perhaps someone has an idea what could be wrong?

**Comment by Arcanemagus** [comment]
The provider for the Markdown language built into Atom (language-gfm) has a bug in the currently released version where _all_ source code in \`\`\` blocks is marked as the full source (eg `source.ruby`) instead of embedded source code (eg `source.embedded.ruby`). This has been fixed in the current master version of that language, but as the version Atom uses is tied to releases I'm not sure when that will be released out to users.

As a workaround you can just install the `language-markdown` package which properly denotes embedded source code (among many other fixes).

**Comment by alexanderadam** [comment]
thank you for this information and extra points for mentioning the work around!
Awesome! :tada:
