### ISSUE TITLE
rubocop linting on github markdown file

### ISSUE THREAD

**Issue by mschuchard** [AtomLinter/linter-rubocop#110]
I was editing a github markdown for serverspec which does contain `"triple-backtick"ruby` in it and, upon saving, Rubocop linted it.  The file is being identified as github markdown by atom.  I checked the index.coffee and am not sure why Rubocop is linting this.  Linter-ruby did not attempt to lint this file.

**Comment by Arcanemagus** [comment]
This is a bug in the version of the `language-gfm` package included in Atom, I believe it is fixed in the v1.6.0 betas.

For some bizarre reason that package used to mark embedded code blocks as the full source code, for example `source.ruby` instead of `source.embedded.ruby`. This meant that when your cursor was inside that block Atom was claiming you were editing regular Ruby code, so the linters would run.

If you can't update to the v1.6.0 betas for any reason, simply install `language-markdown` and disable `language-gfm`.

**Comment by mschuchard** [comment]
Indeed it is version 1.5.3 < 1.6.x, but still curious why linter-rubocop executed and not linter-ruby.

**Comment by Arcanemagus** [comment]
I'm not sure on that... it's possible that it was executing and the message it was giving just wasn't understood by the regex that parses it so it never forwarded on the message?
