### ISSUE TITLE
.rubocop-http* littered throughout project

### ISSUE THREAD

**Issue by sbfaulkner** [AtomLinter/linter-rubocop#114]
when my .rubocop.yml inherits from a remote config file, the local cached copy of that remote file gets littered throughout my project (I assume rubocop is run with a different working directory depending on the file being linted?) ... any way to prevent this? (current workaround is to just add a .gitignore rule, but that doesn't help with the litter)

**Comment by caseywebdev** [comment]
The linter has to be run with the working directory set to the parent directory of the file being linted so the `rubocop` executable can property traverse up the file tree to the nearest `.rubocop.yml`. It's entirely reasonable to have a main project `.rubocop.yml` as well as a more lenient one in a `spec` folder, for example. In theory we *could* duplicate this traversal work in the linter plugin, but honestly it seems like this is an issue with `rubocop` itself, which really should be saving that cached copy right next to the origin `.rubocop.yml` instead of naively saving it in `.`.

**Comment by sbfaulkner** [comment]
@caseywebdev that sounds right... I'll raise this "over there" :-)

**Comment by sbfaulkner** [comment]
hmm... just did a quick test... and running rubocop in a subfolder doesn't leave the cached copy in the current folder... maybe related to explicit --config option or something?

**Comment by caseywebdev** [comment]
That's odd. [You can see the default args here](https://github.com/AtomLinter/linter-rubocop/blob/65fa0a721377d6e8e32d5ebd7e662041cdf17400/index.coffee#L8), but none of those stand out to me as something that should affect where the cached copy is saved.

**Comment by Arcanemagus** [comment]
Closing this as this is a `rubocop` issue. We have _nothing_ to do with how it's managing the cached external config files that it downloads, so if it isn't cleaning them up that's something they need to fix 😉.
