### ISSUE TITLE
Infer TargetRubyVersion from .ruby_version file

### ISSUE THREAD

**Issue by blimmer** [AtomLinter/linter-rubocop#195]
Rubocop will default to reading the `.ruby_version` file if the `TargetRubyVersion` parameter is not present in your rubocop configuration. [Here's the PR](https://github.com/bbatsov/rubocop/pull/3228) that implemented that behavior on the rubocop side.

It would be nice to add that behavior to this linter.

**Comment by maschwenk** [comment]
If you look at this PR, they actually slightly modified the logic to make it so that if you define TargetRubyVersion, it'll still take precedence over `.ruby-version`. So, if you remove `TargetRubyVersion` from your `.rubocop.yml` you should see that this functionality already works, no new code required. https://github.com/bbatsov/rubocop/pull/3261

**Comment by blimmer** [comment]
I don't have TargetRubyVersion set in my rubocop config and I'm getting warnings about the safe navigation operator in my editor with a 2.3 ruby version file. When I run rubocop from the command line I don't get these errors.

**Comment by maschwenk** [comment]
Ahh I see what's happening. The problem is that the linter is running `rubocop` in the directory that the file being linted is located. So if you're linting a file in `/specs` and `.ruby-version` is in the root folder, it's running `rubocop` in `/specs` and therefore not finding the `.ruby-version` file. I will investigate further.

**Comment by blimmer** [comment]
Ah sure that makes sense. Thanks for investigating!

**Comment by chrishough** [comment]
+1

**Comment by maschwenk** [comment]
Please let me know if the fix above resolved your issue. Thanks!

**Comment by blimmer** [comment]
@maschwenk looks great! thank you, this is going to help me out a ton!!
