### ISSUE TITLE
Object.dirname is deprecated. Error from Atom Deprecation Cop

### ISSUE THREAD

**Issue by cameck** [AtomLinter/linter-rubocop#244]
Argument to `path.dirname` must be a string
```
Object.dirname (/Applications/Atom.app/Contents/Resources/app/src/electron-shims.js:9:10)
getProjectDirectory (#{user_path}.atom/packages/linter-rubocop/src/index.js:67:72)
Object.<anonymous> (#{user_path}.atom/packages/linter-rubocop/src/index.js:233:19)
Generator.next (null:null:null)
step (#{user_path}.atom/packages/linter-rubocop/src/index.js:11:273)
<unknown> (#{user_path}.atom/packages/linter-rubocop/src/index.js:11:443)
```

**Comment by Arcanemagus** [comment]
@maschwenk This can be fixed by checking that `textEditor.getpath()` returned a value in these two locations:
https://github.com/AtomLinter/linter-rubocop/blob/26d8b9aad2895b3893660c9137e6183fb52e4b21/src/index.js#L141
https://github.com/AtomLinter/linter-rubocop/blob/26d8b9aad2895b3893660c9137e6183fb52e4b21/src/index.js#L180
