### ISSUE TITLE
Fix on save option

### ISSUE THREAD

**Issue by ericandrewlewis** [AtomLinter/linter-rubocop#271]
Hey - thanks for this linter, it is awesome!

It would be cool to have an option to run Rubocop fix mode on save.

**Comment by vzamanillo** [comment]
Hi Eric!

we can try to exec Rubocop with [autocorrect](https://rubocop.readthedocs.io/en/latest/auto_correct/) for the whole file, today is not possible to give a [solution](https://steelbrain.me/linter/types/linter-message-v2.html) to each offense to the linter because rubocop does not return the correction range and text individually.

The ideal should be
- An automated file correction via configuration option _Autocorrect on save_
- A new entry in contextual menu (right click menu) to autocorrect on demand (rel https://github.com/AtomLinter/linter-eslint/pull/963).

**Comment by vzamanillo** [comment]
Implemented on #346
