### ISSUE TITLE
Failed to Spawn rubocop ENOENT on newest version of atom 1.3.1

### ISSUE THREAD

**Issue by lagerdeveloper** [AtomLinter/linter-rubocop#91]

**Comment by lagerdeveloper** [comment]
I am using rvm for ruby with ruby version 2.2.3
doing apm install linter-rubocop after apm install linter
Every time I open atom from the desktop application get error that rubocop has failed to spawn but when opening atom from the terminal rubocop loads just fine, need help?

**Comment by Arcanemagus** [comment]
Are you on OS X? Apple decided it would be a brilliant idea to give applications launched from the GUI an empty environment, meaning they can't find anything.

You can either specify the full path to rubocop in the settings, or always launch Atom from a terminal environment. There is a bit of work on fixing this Atom side, but it won't land for a while yet from the look of it.

**Comment by ericbrooke** [comment]
@Arcanemagus are you referring to "linter-rubocop":
  executablePath: "~/.rvm/gems/ruby-2.3.0/bin/rubocop"

**Comment by Arcanemagus** [comment]
@ericbrooke If you are using `rvm` you need to create a wrapper script. `rvm` by default uses a shell macro to determine the right path for some bizarre reason. This means that when an external program tries to run things that `rvm` is managing they fail due to the macro not being defined.

**Comment by benhutchins** [comment]
I was actually getting this same error and after investigation found it was due to the version of rubocop. See #101. So there are more possibilities besides rubocop path being incorrect. If, after ensuring the command path is correct, it still doesn't work test your rubocop command manually by running:

```rubocop --cache false --force-exclusion -f json some_file.rb```

Make sure you specify the correct `rubocop` bin as well. If you get an error from that however, then it's your rubocop version.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response from the original filer and the likelihood that this is a user configuration issue.

(Thanks for the pointer to #101 for people finding this by search @benhutchins!)
