### ISSUE TITLE
How to make it work with RVM

### ISSUE THREAD

**Issue by andyentity** [AtomLinter/linter-rubocop#98]
I provided the full correct path to rubocop in the configuration and now I am getting the following error:
```
Error: /usr/bin/env: ruby_executable_hooks: No such file or directory
```
This is probably because I am using RVM. If I want to use ruby in the shell, 
`source ~/.rvm/scripts/rvm` has to be evaluated first. The script is setting all the environment variables and stuff that are needed for the shell to find everything.

How can I tell linter-rubocop (or Atom) to do this?

**Comment by Arcanemagus** [comment]
You will need to create a rvm [wrapper script](https://rvm.io/deployment/init-d) and set that to the executable path in Atom.

**Comment by andyentity** [comment]
Now I'm getting the following error:

```
Error: invalid option: --cache
/home/andreas/.rvm/gems/ruby-2.2.1/gems/rubocop-0.31.0/lib/rubocop/options.rb:68:in `parse'
/home/andreas/.rvm/gems/ruby-2.2.1/gems/rubocop-0.31.0/lib/rubocop/cli.rb:21:in `run'
/home/andreas/.rvm/gems/ruby-2.2.1/gems/rubocop-0.31.0/bin/rubocop:13:in `block in <top (required)>'
/home/andreas/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/home/andreas/.rvm/gems/ruby-2.2.1/gems/rubocop-0.31.0/bin/rubocop:12:in `<top (required)>'
/home/andreas/.rvm/gems/ruby-2.2.1/bin/rubocop:23:in `load'
/home/andreas/.rvm/gems/ruby-2.2.1/bin/rubocop:23:in `<main>'
/home/andreas/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/home/andreas/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
    at /home/andreas/.atom/packages/linter-rubocop/index.coffee:30:15
```

The wrapper script itself is working fine, I can use rubocop without `source`-ing with it.

**Comment by whoward** [comment]
@andyentity you may have a better time installing it to your system ruby, it should be on your PATH so you shouldn't need to do any configuration and you won't have to remember the syntax for regenerating the wrapper script every time you update rubocop

@Arcanemagus what do you think about doing something like injecting the project folder path into the configuration variable and then using binstubs?  Example:
`#{projectDirectory}/bin/rubocop` or `#{projectDirectory}/bin/bundle exec rubocop`

I'm asking mostly because I tend to have multiple projects that run with multiple versions of rubocop (some of which are out of my direct control) and this might be a smarter way to tackle this problem.  Is that a crazy idea?

**Comment by caseywebdev** [comment]
@andyentity You'll need to upgrade rubocop. The version you're using isn't supported.

**Comment by Arcanemagus** [comment]
@whoward Are you talking about something like what [linter-pylint](https://github.com/AtomLinter/linter-pylint) does?

**Comment by whoward** [comment]
@Arcanemagus i don't use that one but from the docs yeah the `%p` option sounds like the idea i'm talking about

**Comment by andyentity** [comment]
Upgrading to the lastest rubocop version did the trick. Everything is working! Thanks a lot.

**Comment by Arcanemagus** [comment]
@whoward If you could file an issue to track implementing that, that would be great :wink:.

@andyentity glad to hear it :smile:.

**Comment by whoward** [comment]
@Arcanemagus no problem - see #100

**Comment by cerdiogenes** [comment]
Using [000-project-shell-env](https://github.com/ddiachkov/atom-project-shell-env) you don't need to specify a path. You can just use linter-rubocop defaults.
